In [1]:
import numpy as np

## Create a NumPy array:

In [3]:
arr = np.array([1, 2, 3, 4, 5], dtype=int)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
### Create array with datatype

arr = np.array([1, 2, 3, 4, 5], dtype=int)
print(arr)
print(arr.dtype)

arr = np.array([1, 2, 3, 4, 5], dtype=float)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float64
